matrix:
  include:
    sudo: required
    language: node_js
    services:
      - docker
    dist: trusty
    node_js:
      - "8"
    cache:
      directories:
        - node_modules
        - $HOME/.npm
    before_install:
      - npm install -g npm@6
    install:
      - npm install
    script:
      - travis_retry npm run lint
    after_success:
      - npx semantic-release
      - export VERSION=$(cat .version)
      - export MAJOR=$(echo $VERSION | sed -n 's/^v\?\([[:digit:]]\+\).*/\1/p')
      - ./scripts/push-container.sh
    branches:
      except:
        - /^v\d+\.\d+\.\d+$/
